
function onCreate()
	setProperty('skipCountdown', true)
	setProperty('showRating', false)
	setProperty('showComboNum', false)
	precacheImage('greenhillzone/greenhillgrass')
	precacheImage('greenhillzone/greenhillzonetree')
	precacheImage('greenhillzone/rockymountains')
	precacheImage('greenhillzone/greenhillzonebgtreesandrocks')
	precacheImage('greenhillzone/greenhillzoneskygradient')
	precacheImage('greenhillzone/blue-vignette')
	precacheImage('greenhillzone/angelisland/redvignette')
	makeLuaSprite('grass', 'greenhillzone/greenhillgrass',-2235,585)
	makeLuaSprite('tree1', 'greenhillzone/greenhillzonetree',-500,-900)
	makeLuaSprite('tree2', 'greenhillzone/greenhillzonetree',1300,-600)
	makeLuaSprite('sky', 'greenhillzone/greenhillzoneskygradient',-3000,-1200)
	makeLuaSprite('pointythings', 'greenhillzone/rockymountains',-1000,-550)
	makeLuaSprite('treesandrocks', 'greenhillzone/greenhillzonebgtreesandrocks', -1300, -30)
	makeAnimatedLuaSprite('smallwater', 'greenhillzone/smallwaterfall', -750, 120)
	makeAnimatedLuaSprite('largewater', 'greenhillzone/largewaterfall', 1465, 115)
	makeAnimatedLuaSprite('ocean', 'greenhillzone/ocean', -1500, 360)
	makeLuaSprite('tree3', 'greenhillzone/greenhillzonetree',-1400,-400)
	makeAnimatedLuaSprite('purpr1', 'greenhillzone/purpurflower', -40, 300)
	makeAnimatedLuaSprite('purpr2', 'greenhillzone/purpurflower', 920, 300)
	makeAnimatedLuaSprite('sun1', 'greenhillzone/sunflower', 1250, -200)
	makeAnimatedLuaSprite('sun2', 'greenhillzone/sunflower', -900, -200)
	addAnimationByPrefix('sun1', 'tick', 'tick', 24, true)
	addAnimationByPrefix('sun2', 'tick', 'tick', 24, true)
	addAnimationByPrefix('smallwater', 'drowning', 'drowning', 24, true)
	addAnimationByPrefix('largewater', 'bigdrowning', 'bigdrowning', 24, true)
	addAnimationByPrefix('ocean', 'sinking', 'sinking', 24, true)
	addAnimationByPrefix('purpr1', 'bouncing', 'bouncing', 24,false)
	addAnimationByPrefix('purpr2', 'bouncing', 'bouncing', 24,false)
	scaleObject('sky', 16,8)
	scaleObject('pointythings', 3.0,3.0)
	scaleObject('treesandrocks', 3.0,3.0)
	scaleObject('smallwater', 1.5,1.5)
	scaleObject('largewater', 3.0,3.0)
	scaleObject('ocean', 3.5,3.5)
	scaleObject('tree2',3.0,3.0)
	scaleObject('tree3',3.0,3.0)
	scaleObject('grass',5.0,5.0)
	scaleObject('tree1',3.0,3.0)
	scaleObject('purpr1', 1.75,1.75)
	scaleObject('purpr2', 1.75,1.75)
	scaleObject('sun1', 1.75,1.75)
	scaleObject('sun2', 1.75,1.75)
	addLuaSprite('sky')
	addLuaSprite('pointythings')
	addLuaSprite('treesandrocks')
	addLuaSprite('smallwater')
	addLuaSprite('largewater')
	addLuaSprite('ocean')
	addLuaSprite('tree2')
	addLuaSprite('tree3')
	addLuaSprite('tree1')
	addLuaSprite('grass')
	addLuaSprite('purpr1')
	addLuaSprite('purpr2')
	addLuaSprite('sun1')
	addLuaSprite('sun2')
	setProperty('purpr2.flipX', true)
	playAnim('ocean', 'sinking')
	playAnim('largewater', 'drowning')
	playAnim('smallwater', 'bigdrowning')
	playAnim('sun1', 'tick')
	playAnim('sun2', 'tick')
	setScrollFactor('pointythings',0.1,0.1)
	setScrollFactor('treesandrocks',.25,.05)
	setScrollFactor('smallwater',.25,.05)
	setScrollFactor('largewater',.25,.05)
	setScrollFactor('ocean',0.8,0.05)
	makeLuaSprite('shader', 'greenhillzone/blue-vignette',0,0)
	scaleObject('shader', 4.0, 4.0);
	addLuaSprite('shader')
	setProperty('shader.alpha',.4)
	setObjectCamera('shader','hud')
	debugPrint(ogMiddleScrollSetting)
	end
	
function onCreatePost()
	local oldxx = getProperty('dad.cameraPosition[0]')
	local oldyy = getProperty('dad.cameraPosition[1]')
	--local ogMiddleScrollSetting = getPropertyFromClass('backend.ClientPrefs','data.middleScroll')
	--setPropertyFromClass('backend.ClientPrefs','data.middleScroll',false)
end
function onDestroy()
	--setPropertyFromClass('backend.ClientPrefs','data.middleScroll',ogMiddleScrollSetting)
end
function onBeatHit()
    if curBeat % 2 == 1 then
		playAnim('purpr1', 'bouncing', true)
    end
    if curBeat % 2 == 0 then
		playAnim('purpr2', 'bouncing', true)
    end
end
function onStepHit()
	if curStep == 1 then
	end
end
function onTweenCompleted(tag)
	if tag == 'meAlpha' then
		removeLuaSprite('do',true)
		removeLuaSprite('you',true)
		removeLuaSprite('wanna',true)
		removeLuaSprite('play',true)
		removeLuaSprite('with',true)
		removeLuaSprite('me')
		setProperty('coverstuffhud.alpha', 0)
		removeLuaSprite('cutscene1',true)
		removeLuaSprite('oogabooga',true)
		setProperty('cameraSpeed', 1.7)
		setProperty('defaultCamZoom', .75)
		cameraFlash('other','ff0000',.3,true)
		
	end
	if tag == 'stare' then
	setProperty('defaultCamZoom', 1.3)
	end
	if tag == 'stopstaring' then
	setProperty('defaultCamZoom', .75)
	end
end